app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check

logout:
    path:   /logout

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
